// Simple client-side script for the status page.

/*
Responsibilities:
- Fetch the latest monitor state JSON generated by the Python script.
- Render monitoring health information and the latest announcement.
- Enforce the 30-day visibility rule entirely in the browser.
*/

// Relative path from the page to the JSON state file committed by the monitor.
const STATE_URL = "../state/state.json";

// Convert an ISO datetime string (from Python) into a human-readable string
// based on the user's local timezone and locale.
function formatDate(isoString) {
  if (!isoString) return "–";
  const date = new Date(isoString);
  if (Number.isNaN(date.getTime())) return isoString;
  return date.toLocaleString(undefined, {
    year: "numeric",
    month: "short",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
  });
}

// Return the whole number of days between two Date objects.
function daysBetween(a, b) {
  const msPerDay = 24 * 60 * 60 * 1000;
  return Math.floor((b.getTime() - a.getTime()) / msPerDay);
}

// Fetch state JSON and update all UI elements on the page.
async function loadState() {
  const monitoringEl = document.getElementById("status-monitoring");
  const lastRunEl = document.getElementById("status-last-run");
  const lastResultEl = document.getElementById("status-last-result");
  const lastErrorEl = document.getElementById("status-last-error");
  const annEmptyEl = document.getElementById("announcement-empty");

  try {
    const response = await fetch(STATE_URL, {
      cache: "no-store",
    });

    if (!response.ok) {
      throw new Error(`HTTP ${response.status}`);
    }

    const data = await response.json();

    const monitoringEnabled = Boolean(data.monitoring_enabled);
    monitoringEl.textContent = monitoringEnabled ? "ON" : "OFF";
    monitoringEl.classList.toggle("status-value--muted", !monitoringEnabled);

    lastRunEl.textContent = data.last_run_time ? formatDate(data.last_run_time) : "Never";

    if (data.last_run_status === "success") {
      lastResultEl.textContent = "Success";
      lastResultEl.style.color = "#22c55e";
    } else if (data.last_run_status === "failure") {
      lastResultEl.textContent = "Failure";
      lastResultEl.style.color = "#f97316";
    } else {
      lastResultEl.textContent = "Unknown";
      lastResultEl.style.color = "";
    }

    if (data.error_history && data.error_history.length > 0) {
      // Show the most recent error
      const latestError = data.error_history[0];
      lastErrorEl.textContent = `${latestError.message} (${formatDate(latestError.timestamp)})`;
      lastErrorEl.classList.remove("status-value--muted");
    } else if (data.last_error_message) {
      // Fallback for legacy state
      lastErrorEl.textContent = data.last_error_message;
      lastErrorEl.classList.remove("status-value--muted");
    } else {
      lastErrorEl.textContent = "None";
      lastErrorEl.classList.add("status-value--muted");
    }

    // Handle Announcements
    const announcementListEl = document.getElementById("announcement-list");
    const template = document.getElementById("announcement-template");

    // Clear existing list
    announcementListEl.innerHTML = "";

    let announcements = [];
    if (data.announcement_history) {
      announcements = data.announcement_history;
    } else if (data.last_announcement) {
      // Legacy support
      announcements = [data.last_announcement];
    }

    const now = new Date();
    let visibleCount = 0;

    announcements.forEach(ann => {
      if (!ann.first_detected) return;

      const firstDetected = new Date(ann.first_detected);
      const age = daysBetween(firstDetected, now);

      if (!Number.isNaN(firstDetected.getTime()) && age <= 30) {
        const clone = template.content.cloneNode(true);

        clone.querySelector(".announcement__text").textContent = ann.text || "";
        clone.querySelector(".announcement-date").textContent = formatDate(ann.first_detected);

        const linkWrapper = clone.querySelector(".announcement__links");
        const pdfLink = clone.querySelector(".announcement-pdf");

        if (ann.pdf_url) {
          pdfLink.href = ann.pdf_url;
          linkWrapper.hidden = false;
        } else {
          linkWrapper.hidden = true;
        }

        announcementListEl.appendChild(clone);
        visibleCount++;
      }
    });

    if (visibleCount > 0) {
      annEmptyEl.hidden = true;
    } else {
      annEmptyEl.hidden = false;
    }

  } catch (error) {
    // If anything goes wrong (network error, invalid JSON, etc), fall back to
    // a safe, readable error state instead of breaking the page.
    monitoringEl.textContent = "Unknown";
    monitoringEl.classList.add("status-value--muted");
    lastRunEl.textContent = "Unavailable";
    lastResultEl.textContent = "Error loading state";
    lastResultEl.style.color = "#f97316";
    lastErrorEl.textContent = String(error);
    lastErrorEl.classList.remove("status-value--muted");

    document.getElementById("announcement-list").innerHTML = "";
    document.getElementById("announcement-empty").hidden = false;
  }
}

// Run as soon as the DOM is ready. This keeps the HTML fully static so the
// page can be hosted on any static file host (including GitHub Pages).
document.addEventListener("DOMContentLoaded", loadState);

